// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public final class Algocomm {
  private Algocomm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_StartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_StartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_StatusString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_StatusString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_ObstacleString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_ObstacleString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_ImageID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_ImageID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_RobotPosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_RobotPosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_MoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_MoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algo_RadiiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algo_RadiiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016algocomm.proto\022\004algo\"\007\n\005Empty\"\036\n\rStart" +
      "Response\022\r\n\005start\030\001 \001(\010\"\036\n\014StatusString\022" +
      "\016\n\006status\030\001 \001(\t\"#\n\016ObstacleString\022\021\n\tobs" +
      "tacles\030\001 \001(\t\"\025\n\007ImageID\022\n\n\002id\030\001 \001(\t\")\n\rR" +
      "obotPosition\022\030\n\020robotCoordinates\030\001 \001(\t\"7" +
      "\n\013MoveRequest\022\026\n\016radius_indexed\030\001 \001(\005\022\020\n" +
      "\010distance\030\002 \001(\001\"%\n\014MoveResponse\022\025\n\rtime_" +
      "required\030\001 \001(\001\"\036\n\rRadiiResponse\022\r\n\005radii" +
      "\030\001 \003(\0012\343\002\n\004algo\0229\n\022ReceiveCoordinates\022\013." +
      "algo.Empty\032\024.algo.ObstacleString\"\000\022-\n\004Mo" +
      "ve\022\021.algo.MoveRequest\032\022.algo.MoveRespons" +
      "e\022,\n\010GetRadii\022\013.algo.Empty\032\023.algo.RadiiR" +
      "esponse\0221\n\013MoveVirtual\022\023.algo.RobotPosit" +
      "ion\032\013.algo.Empty\"\000\022+\n\013TakePicture\022\r.algo" +
      ".ImageID\032\013.algo.Empty\"\000\0221\n\014UpdateStatus\022" +
      "\022.algo.StatusString\032\013.algo.Empty\"\000\0220\n\nCh" +
      "eckStart\022\013.algo.Empty\032\023.algo.StartRespon" +
      "se\"\000B\020\n\014com.mdp.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_algo_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_algo_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_algo_StartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_algo_StartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_StartResponse_descriptor,
        new java.lang.String[] { "Start", });
    internal_static_algo_StatusString_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_algo_StatusString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_StatusString_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_algo_ObstacleString_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_algo_ObstacleString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_ObstacleString_descriptor,
        new java.lang.String[] { "Obstacles", });
    internal_static_algo_ImageID_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_algo_ImageID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_ImageID_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_algo_RobotPosition_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_algo_RobotPosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_RobotPosition_descriptor,
        new java.lang.String[] { "RobotCoordinates", });
    internal_static_algo_MoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_algo_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_MoveRequest_descriptor,
        new java.lang.String[] { "RadiusIndexed", "Distance", });
    internal_static_algo_MoveResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_algo_MoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_MoveResponse_descriptor,
        new java.lang.String[] { "TimeRequired", });
    internal_static_algo_RadiiResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_algo_RadiiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algo_RadiiResponse_descriptor,
        new java.lang.String[] { "Radii", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
