// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.Empty)
    com.google.protobuf.MessageOrBuilder {
}
