// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface MoveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.MoveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0-based index of radius in the indices array.
   * `0` for straight moves.
   * Set negative to have the turning center on the left, positive to have
   * the turning center on the right.
   * </pre>
   *
   * <code>int32 radius_indexed = 1;</code>
   */
  int getRadiusIndexed();

  /**
   * <pre>
   * Distance to move.
   * Specified in units of metres.
   * Use negative distances for reversing.
   * </pre>
   *
   * <code>double distance = 2;</code>
   */
  double getDistance();
}
