// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

/**
 * Protobuf type {@code algo.MoveRequest}
 */
public  final class MoveRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:algo.MoveRequest)
    MoveRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MoveRequest.newBuilder() to construct.
  private MoveRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MoveRequest() {
    radiusIndexed_ = 0;
    distance_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MoveRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            radiusIndexed_ = input.readInt32();
            break;
          }
          case 17: {

            distance_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mdp.grpc.Algocomm.internal_static_algo_MoveRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mdp.grpc.Algocomm.internal_static_algo_MoveRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mdp.grpc.MoveRequest.class, com.mdp.grpc.MoveRequest.Builder.class);
  }

  public static final int RADIUS_INDEXED_FIELD_NUMBER = 1;
  private int radiusIndexed_;
  /**
   * <pre>
   * 0-based index of radius in the indices array.
   * `0` for straight moves.
   * Set negative to have the turning center on the left, positive to have
   * the turning center on the right.
   * </pre>
   *
   * <code>int32 radius_indexed = 1;</code>
   */
  public int getRadiusIndexed() {
    return radiusIndexed_;
  }

  public static final int DISTANCE_FIELD_NUMBER = 2;
  private double distance_;
  /**
   * <pre>
   * Distance to move.
   * Specified in units of metres.
   * Use negative distances for reversing.
   * </pre>
   *
   * <code>double distance = 2;</code>
   */
  public double getDistance() {
    return distance_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (radiusIndexed_ != 0) {
      output.writeInt32(1, radiusIndexed_);
    }
    if (distance_ != 0D) {
      output.writeDouble(2, distance_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (radiusIndexed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, radiusIndexed_);
    }
    if (distance_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, distance_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mdp.grpc.MoveRequest)) {
      return super.equals(obj);
    }
    com.mdp.grpc.MoveRequest other = (com.mdp.grpc.MoveRequest) obj;

    boolean result = true;
    result = result && (getRadiusIndexed()
        == other.getRadiusIndexed());
    result = result && (
        java.lang.Double.doubleToLongBits(getDistance())
        == java.lang.Double.doubleToLongBits(
            other.getDistance()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RADIUS_INDEXED_FIELD_NUMBER;
    hash = (53 * hash) + getRadiusIndexed();
    hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDistance()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mdp.grpc.MoveRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdp.grpc.MoveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mdp.grpc.MoveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mdp.grpc.MoveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mdp.grpc.MoveRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code algo.MoveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:algo.MoveRequest)
      com.mdp.grpc.MoveRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mdp.grpc.Algocomm.internal_static_algo_MoveRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mdp.grpc.Algocomm.internal_static_algo_MoveRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mdp.grpc.MoveRequest.class, com.mdp.grpc.MoveRequest.Builder.class);
    }

    // Construct using com.mdp.grpc.MoveRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      radiusIndexed_ = 0;

      distance_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mdp.grpc.Algocomm.internal_static_algo_MoveRequest_descriptor;
    }

    @java.lang.Override
    public com.mdp.grpc.MoveRequest getDefaultInstanceForType() {
      return com.mdp.grpc.MoveRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.mdp.grpc.MoveRequest build() {
      com.mdp.grpc.MoveRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mdp.grpc.MoveRequest buildPartial() {
      com.mdp.grpc.MoveRequest result = new com.mdp.grpc.MoveRequest(this);
      result.radiusIndexed_ = radiusIndexed_;
      result.distance_ = distance_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mdp.grpc.MoveRequest) {
        return mergeFrom((com.mdp.grpc.MoveRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mdp.grpc.MoveRequest other) {
      if (other == com.mdp.grpc.MoveRequest.getDefaultInstance()) return this;
      if (other.getRadiusIndexed() != 0) {
        setRadiusIndexed(other.getRadiusIndexed());
      }
      if (other.getDistance() != 0D) {
        setDistance(other.getDistance());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mdp.grpc.MoveRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mdp.grpc.MoveRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int radiusIndexed_ ;
    /**
     * <pre>
     * 0-based index of radius in the indices array.
     * `0` for straight moves.
     * Set negative to have the turning center on the left, positive to have
     * the turning center on the right.
     * </pre>
     *
     * <code>int32 radius_indexed = 1;</code>
     */
    public int getRadiusIndexed() {
      return radiusIndexed_;
    }
    /**
     * <pre>
     * 0-based index of radius in the indices array.
     * `0` for straight moves.
     * Set negative to have the turning center on the left, positive to have
     * the turning center on the right.
     * </pre>
     *
     * <code>int32 radius_indexed = 1;</code>
     */
    public Builder setRadiusIndexed(int value) {
      
      radiusIndexed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0-based index of radius in the indices array.
     * `0` for straight moves.
     * Set negative to have the turning center on the left, positive to have
     * the turning center on the right.
     * </pre>
     *
     * <code>int32 radius_indexed = 1;</code>
     */
    public Builder clearRadiusIndexed() {
      
      radiusIndexed_ = 0;
      onChanged();
      return this;
    }

    private double distance_ ;
    /**
     * <pre>
     * Distance to move.
     * Specified in units of metres.
     * Use negative distances for reversing.
     * </pre>
     *
     * <code>double distance = 2;</code>
     */
    public double getDistance() {
      return distance_;
    }
    /**
     * <pre>
     * Distance to move.
     * Specified in units of metres.
     * Use negative distances for reversing.
     * </pre>
     *
     * <code>double distance = 2;</code>
     */
    public Builder setDistance(double value) {
      
      distance_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Distance to move.
     * Specified in units of metres.
     * Use negative distances for reversing.
     * </pre>
     *
     * <code>double distance = 2;</code>
     */
    public Builder clearDistance() {
      
      distance_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:algo.MoveRequest)
  }

  // @@protoc_insertion_point(class_scope:algo.MoveRequest)
  private static final com.mdp.grpc.MoveRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mdp.grpc.MoveRequest();
  }

  public static com.mdp.grpc.MoveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MoveRequest>
      PARSER = new com.google.protobuf.AbstractParser<MoveRequest>() {
    @java.lang.Override
    public MoveRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MoveRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MoveRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MoveRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mdp.grpc.MoveRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

