// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.mdp.grpc;

public interface MoveResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MoveResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Estimated time for move to complete.
   * Specified in units of seconds.
   * </pre>
   *
   * <code>double time_required = 1;</code>
   */
  double getTimeRequired();
}
