// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface ObstacleStringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.ObstacleString)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string obstacles = 1;</code>
   */
  java.lang.String getObstacles();
  /**
   * <code>string obstacles = 1;</code>
   */
  com.google.protobuf.ByteString
      getObstaclesBytes();
}
