// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface RadiiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.RadiiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Array of available turn radii.
   * The first value is +inf for straight line motion.
   * </pre>
   *
   * <code>repeated double radii = 1;</code>
   */
  java.util.List<java.lang.Double> getRadiiList();
  /**
   * <pre>
   * Array of available turn radii.
   * The first value is +inf for straight line motion.
   * </pre>
   *
   * <code>repeated double radii = 1;</code>
   */
  int getRadiiCount();
  /**
   * <pre>
   * Array of available turn radii.
   * The first value is +inf for straight line motion.
   * </pre>
   *
   * <code>repeated double radii = 1;</code>
   */
  double getRadii(int index);
}
