// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface RobotPositionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.RobotPosition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string robotCoordinates = 1;</code>
   */
  java.lang.String getRobotCoordinates();
  /**
   * <code>string robotCoordinates = 1;</code>
   */
  com.google.protobuf.ByteString
      getRobotCoordinatesBytes();
}
