// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algocomm.proto

package com.mdp.grpc;

public interface StartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:algo.StartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool start = 1;</code>
   */
  boolean getStart();
}
