// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.mdp.grpc;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ObstacleString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ObstacleString_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RobotPosition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RobotPosition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MoveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MoveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MoveResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MoveResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RadiiResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RadiiResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"\007\n\005Empty\"#\n\016ObstacleString\022" +
      "\021\n\tobstacles\030\001 \001(\t\")\n\rRobotPosition\022\030\n\020r" +
      "obotCoordinates\030\001 \001(\t\"7\n\013MoveRequest\022\026\n\016" +
      "radius_indexed\030\001 \001(\005\022\020\n\010distance\030\002 \001(\001\"%" +
      "\n\014MoveResponse\022\025\n\rtime_required\030\001 \001(\001\"\036\n" +
      "\rRadiiResponse\022\r\n\005radii\030\001 \003(\0012\251\001\n\004algo\022/" +
      "\n\022ReceiveCoordinates\022\006.Empty\032\017.ObstacleS" +
      "tring\"\000\022#\n\004Move\022\014.MoveRequest\032\r.MoveResp" +
      "onse\022\"\n\010GetRadii\022\006.Empty\032\016.RadiiResponse" +
      "\022\'\n\013MoveVirtual\022\016.RobotPosition\032\006.Empty\"" +
      "\000B\020\n\014com.mdp.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_ObstacleString_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ObstacleString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ObstacleString_descriptor,
        new java.lang.String[] { "Obstacles", });
    internal_static_RobotPosition_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RobotPosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RobotPosition_descriptor,
        new java.lang.String[] { "RobotCoordinates", });
    internal_static_MoveRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MoveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MoveRequest_descriptor,
        new java.lang.String[] { "RadiusIndexed", "Distance", });
    internal_static_MoveResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MoveResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MoveResponse_descriptor,
        new java.lang.String[] { "TimeRequired", });
    internal_static_RadiiResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RadiiResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RadiiResponse_descriptor,
        new java.lang.String[] { "Radii", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
